/*
 * uart_console_config.h
 *
 *  Created on: 2023. jul. 11.
 *      Author: Balint
 */

#ifndef _STDIO_UART_CONFIG_H_
#define _STDIO_UART_CONFIG_H_

#define STDIO_UART_RX_QUEUE_LENGTH              8
#define STDIO_UART_TX_AVAIL_QUEUE_LENGTH        16
#define STDIO_UART_TX_READY_QUEUE_LENGTH        STDIO_UART_TX_AVAIL_QUEUE_LENGTH
#define STDIO_UART_WRITE_TASK_PRIORITY          2
#define STDIO_UART_WRITE_TASK_STACKSIZE         configMINIMAL_STACK_SIZE
#define STDIO_UART_TX_BUFFER_DEPTH              configCOMMAND_INT_MAX_OUTPUT_SIZE
#define STDIO_UART_USARTx                       USART3
#define STDIO_UART_USARTx_CLK_ENABLE            __HAL_RCC_USART3_CLK_ENABLE
#define STDIO_UART_USARTx_CLK_DISABLE           __HAL_RCC_USART3_CLK_DISABLE
#define STDIO_UART_USARTx_FORCE_RESET           __HAL_RCC_USART3_FORCE_RESET
#define STDIO_UART_USARTx_RELEASE_RESET         __HAL_RCC_USART3_RELEASE_RESET
#define STDIO_UART_DMAx_CLK_ENABLE              __HAL_RCC_DMA1_CLK_ENABLE
#define STDIO_UART_GPIOx_CLK_ENABLE             __HAL_RCC_GPIOB_CLK_ENABLE
#define STDIO_UART_UARTx_TX_PIN                 GPIO_PIN_11
#define STDIO_UART_UARTx_RX_PIN                 GPIO_PIN_10
#define STDIO_UART_GPIOx_PORT                   GPIOB
#define STDIO_UART_GPIO_AFx_USARTx              GPIO_AF7_USART3
#define STDIO_UART_DMAx_STREAMx                 DMA1_Stream3
#define STDIO_UART_DMA_CHANNELx                 DMA_CHANNEL_4
#define STDIO_UART_USARTx_IRQn                  USART3_IRQn
#define STDIO_UART_USARTx_IRQ_PRIORITY          14
#define STDIO_UART_DMAx_STREAMx_IRQn            DMA1_Stream3_IRQn
#define STDIO_UART_DMAx_STREAMx_IRQ_PRIORITY    14

#endif /* _STDIO_UART_CONFIG_H_ */

