/*
 * uart_console_config.h
 *
 *  Created on: 2023. jul. 11.
 *      Author: Balint
 */

#ifndef _UART_CONSOLE_CONFIG_H_
#define _UART_CONSOLE_CONFIG_H_

#define UART_CONSOLE_RX_QUEUE_LENGTH              8
#define UART_CONSOLE_TX_AVAIL_QUEUE_LENGTH        16
#define UART_CONSOLE_TX_READY_QUEUE_LENGTH        UART_CONSOLE_TX_AVAIL_QUEUE_LENGTH
#define UART_CONSOLE_WRITE_TASK_PRIORITY          2
#define UART_CONSOLE_WRITE_TASK_STACKSIZE         configMINIMAL_STACK_SIZE
#define UART_CONSOLE_TX_BUFFER_DEPTH              configCOMMAND_INT_MAX_OUTPUT_SIZE
#define UART_CONSOLE_USARTx                       USART3
#define UART_CONSOLE_USARTx_CLK_ENABLE            __HAL_RCC_USART3_CLK_ENABLE
#define UART_CONSOLE_USARTx_CLK_DISABLE           __HAL_RCC_USART3_CLK_DISABLE
#define UART_CONSOLE_USARTx_FORCE_RESET           __HAL_RCC_USART3_FORCE_RESET
#define UART_CONSOLE_USARTx_RELEASE_RESET         __HAL_RCC_USART3_RELEASE_RESET
#define UART_CONSOLE_DMAx_CLK_ENABLE              __HAL_RCC_DMA1_CLK_ENABLE
#define UART_CONSOLE_GPIOx_CLK_ENABLE             __HAL_RCC_GPIOB_CLK_ENABLE
#define UART_CONSOLE_UARTx_TX_PIN                 GPIO_PIN_11
#define UART_CONSOLE_UARTx_RX_PIN                 GPIO_PIN_10
#define UART_CONSOLE_GPIOx_PORT                   GPIOB
#define UART_CONSOLE_GPIO_AFx_USARTx              GPIO_AF7_USART3
#define UART_CONSOLE_DMAx_STREAMx                 DMA1_Stream3
#define UART_CONSOLE_DMA_CHANNELx                 DMA_CHANNEL_4
#define UART_CONSOLE_USARTx_IRQn                  USART3_IRQn
#define UART_CONSOLE_USARTx_IRQ_PRIORITY          14
#define UART_CONSOLE_DMAx_STREAMx_IRQn            DMA1_Stream3_IRQn
#define UART_CONSOLE_DMAx_STREAMx_IRQ_PRIORITY    14

#endif /* _UART_CONSOLE_CONFIG_H_ */

